# Generated by Django 5.2.16 on 2026-07-13 21:24

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firme", "0004_partener"),
        ("perioade", "0001_period_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentariu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField()),
                (
                    "creat_la",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comentarii",
                        to="documente.document",
                    ),
                ),
                (
                    "firma",
                    models.ForeignKey(
                        db_column="firma_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comentarii",
                        to="firme.firma",
                    ),
                ),
                (
                    "perioada_contabila",
                    models.ForeignKey(
                        blank=True,
                        db_column="perioada_contabila_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comentarii",
                        to="perioade.perioadacontabila",
                    ),
                ),
                (
                    "utilizator",
                    models.ForeignKey(
                        db_column="utilizator_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comentarii",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "comentariu",
                "verbose_name_plural": "comentarii",
                "db_table": "comentarii",
                "ordering": ("creat_la",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "directie",
                    models.CharField(
                        blank=True,
                        choices=[("primit", "Primit"), ("emis", "Emis")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("serie", models.CharField(blank=True, max_length=20, null=True)),
                ("numar", models.CharField(blank=True, max_length=30, null=True)),
                ("data_document", models.DateField(blank=True, null=True)),
                ("data_scadenta", models.DateField(blank=True, null=True)),
                ("moneda", models.CharField(default="RON", max_length=3)),
                (
                    "valoare_fara_tva",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "valoare_tva",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "valoare_totala",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "stare",
                    models.CharField(
                        choices=[
                            ("draft", "Ciornă"),
                            ("trimis", "Trimis"),
                            ("in_verificare", "În verificare"),
                            ("necesita_clarificari", "Necesită clarificări"),
                            ("acceptat", "Acceptat"),
                            ("procesat", "Procesat"),
                            ("arhivat", "Arhivat"),
                            ("anulat", "Anulat"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("incarcat_dupa_confirmare", models.BooleanField(default=False)),
                ("retentie_extinsa_pana_la", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("sters_la", models.DateTimeField(blank=True, null=True)),
                ("motiv_stergere", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "creat_la",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "actualizat_la",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "cont_financiar",
                    models.ForeignKey(
                        blank=True,
                        db_column="cont_financiar_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documente",
                        to="firme.contfinanciar",
                    ),
                ),
                (
                    "firma",
                    models.ForeignKey(
                        db_column="firma_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documente",
                        to="firme.firma",
                    ),
                ),
                (
                    "incarcat_de",
                    models.ForeignKey(
                        db_column="incarcat_de",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documente_incarcate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partener",
                    models.ForeignKey(
                        blank=True,
                        db_column="partener_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documente",
                        to="firme.partener",
                    ),
                ),
                (
                    "perioada_contabila",
                    models.ForeignKey(
                        db_column="perioada_contabila_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documente",
                        to="perioade.perioadacontabila",
                    ),
                ),
                (
                    "sters_de",
                    models.ForeignKey(
                        blank=True,
                        db_column="sters_de",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documente_sterse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tip_document",
                    models.ForeignKey(
                        db_column="tip_document_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documente",
                        to="firme.tipdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documente",
                "db_table": "documente",
                "ordering": ("-creat_la",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FisierDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("upload_intentie_id", models.UUIDField()),
                ("storage_key", models.CharField(max_length=500)),
                ("nume_original", models.CharField(blank=True, max_length=255, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("dimensiune_bytes", models.BigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                ("numar_pagini", models.IntegerField(blank=True, null=True)),
                ("ordine", models.SmallIntegerField(default=1)),
                ("versiune", models.IntegerField(default=1)),
                (
                    "stare_procesare",
                    models.CharField(
                        choices=[
                            ("in_asteptare", "În așteptare"),
                            ("in_lucru", "În lucru"),
                            ("procesat", "Procesat"),
                            ("eroare", "Eroare"),
                        ],
                        default="in_asteptare",
                        max_length=20,
                    ),
                ),
                ("eroare_procesare", models.TextField(blank=True, null=True)),
                ("incercari_procesare", models.SmallIntegerField(default=0)),
                ("thumbnail_key", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "incarcat_la",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                ("activ", models.BooleanField(default=True)),
                ("sters_la", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fisiere",
                        to="documente.document",
                    ),
                ),
                (
                    "firma",
                    models.ForeignKey(
                        db_column="firma_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fisiere_documente",
                        to="firme.firma",
                    ),
                ),
                (
                    "incarcat_de",
                    models.ForeignKey(
                        db_column="incarcat_de",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fisiere_incarcate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inlocuieste_fisier",
                    models.ForeignKey(
                        blank=True,
                        db_column="inlocuieste_fisier_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiuni_ulterioare",
                        to="documente.fisierdocument",
                    ),
                ),
                (
                    "sters_de",
                    models.ForeignKey(
                        blank=True,
                        db_column="sters_de",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fisiere_sterse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "fișier document",
                "verbose_name_plural": "fișiere document",
                "db_table": "fisiere_document",
                "ordering": ("ordine", "versiune"),
                "managed": False,
            },
        ),
    ]
