# Generated by Django 5.2.16 on 2026-07-14 07:03

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentieUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_key", models.CharField(db_default="", max_length=500)),
                ("nume_original", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "expira_la",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("folosita_la", models.DateTimeField(blank=True, null=True)),
                (
                    "creat_la",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intentii_upload",
                        to="documente.document",
                    ),
                ),
                (
                    "firma",
                    models.ForeignKey(
                        db_column="firma_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intentii_upload",
                        to="firme.firma",
                    ),
                ),
                (
                    "utilizator",
                    models.ForeignKey(
                        db_column="utilizator_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intentii_upload",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "intenție de încărcare",
                "verbose_name_plural": "intenții de încărcare",
                "db_table": "intentii_upload",
                "ordering": ("-creat_la",),
                "managed": False,
            },
        ),
        migrations.RenameField(
            model_name="fisierdocument",
            old_name="upload_intentie_id",
            new_name="upload_intentie",
        ),
        migrations.AlterField(
            model_name="fisierdocument",
            name="upload_intentie",
            field=models.OneToOneField(
                db_column="upload_intentie_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fisier",
                to="documente.intentieupload",
            ),
        ),
    ]
