# Generated by Django 5.2.16 on 2026-07-13 21:24

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firme", "0003_configuration_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipdocument",
            name="tipuri_cont_compatibile",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="tipdocument",
            name="retentie_ani",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Partener",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("furnizor", "Furnizor"),
                            ("client", "Client"),
                            ("ambele", "Furnizor și client"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cui", models.CharField(blank=True, max_length=20, null=True)),
                ("denumire", models.CharField(max_length=255)),
                ("tara", models.CharField(default="RO", max_length=2)),
                ("activ", models.BooleanField(default=True)),
                (
                    "creat_la",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "creat_de",
                    models.ForeignKey(
                        blank=True,
                        db_column="creat_de",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parteneri_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firma",
                    models.ForeignKey(
                        db_column="firma_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parteneri",
                        to="firme.firma",
                    ),
                ),
            ],
            options={
                "verbose_name": "partener",
                "verbose_name_plural": "parteneri",
                "db_table": "parteneri",
                "ordering": ("denumire",),
                "managed": False,
            },
        ),
    ]
